services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    container_name: traefik-reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8888:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    restart: always
    labels:
      - "traefik.enable=true"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    container_name: ${PROJECT_NAME}-frontend
    # ports:
    #   - 80:80
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(`hostels.localhost`)"

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    container_name: ${PROJECT_NAME}-backend
    command: ["bash", "/app/start.sh"]
    env_file:
      - ./backend/envs/.env
    ports:
      - 3000:3000
    depends_on:
      - pgsql
    environment:
      - NODE_ENV=production

  pgsql:
    image: postgres:13
    container_name: ${PROJECT_NAME}-pgsql
    ports:
      - 5432:5432
    env_file:
      - ./backend/envs/.env
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  db_data:
    name: ${PROJECT_NAME}-db-data
