services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    container_name: ${PROJECT_NAME}-frontend
    depends_on:
      - backend
    ports:
      - 9991:80
      
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    container_name: ${PROJECT_NAME}-backend
    command: ["bash", "/app/start.sh"]
    env_file:
      - ./backend/envs/.env
    depends_on:
      - pgsql
    environment:
      - NODE_ENV=production

  pgsql:
    image: postgres:13
    container_name: ${PROJECT_NAME}-pgsql
    env_file:
      - ./backend/envs/.env
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  db_data:
    name: ${PROJECT_NAME}-db-data
